import { useState } from "react";
import { ArrowRight, Bus, CheckCircle, Clock, House, Info, MapPin, PersonSimpleWalk } from "@phosphor-icons/react";
import { clockTime, demoJourneys, money, timeMinutes, total } from "./interviewData.js";

export const defaultMobility = { days: 26, arrival: "06:00", departure: "18:00", buffer: 10, addressConfirmed: false, scheduleConfirmed: false, notes: "", transports: [] };

export function InterviewMobility({ profile, value, onChange, reviewed, onReview, post = "Leblon Power", demoAvailable = true }) {
  const [direction, setDirection] = useState("outbound");
  const journey = demoAvailable ? demoJourneys[profile.name] : null;
  const update = (field, next) => onChange({ ...value, [field]: next });
  const legs = journey?.[direction];
  const daily = journey ? total(journey.outbound, "fare") + total(journey.inbound, "fare") : 0;
  const transportOptions = ["Ônibus", "Metrô", "Trem", "Carro", "Moto", "A pé", "Bicicleta"];
  const toggleTransport = (transport) => update("transports", (value.transports || []).includes(transport) ? value.transports.filter((item) => item !== transport) : [...(value.transports || []), transport]);
  return <section className="iw-mobility" aria-label="Análise de mobilidade">
    <div className="iw-notice"><Info size={18} /><p><b>Simulação de mobilidade</b>Tempos e tarifas demonstrativos. Sem consulta a trânsito, linhas ou disponibilidade real de transporte.</p></div>
    <div className="iw-endpoints"><div><House size={20} /><span><small>Origem declarada</small><b>{profile.location || "Não informada"}</b></span></div><ArrowRight size={18} /><div><MapPin size={20} /><span><small>Posto de trabalho</small><b>{post}</b><small>{demoAvailable ? "Leblon · Rio de Janeiro, RJ" : "Endereço a confirmar"}</small></span></div></div>
    <fieldset className="iw-transport-choice"><legend>Meios de transporte informados pelo candidato</legend><p>Marque todas as opções que podem ser usadas no deslocamento para esta vaga.</p><div>{transportOptions.map((transport) => <label key={transport}><input type="checkbox" checked={(value.transports || []).includes(transport)} onChange={() => toggleTransport(transport)} />{transport}</label>)}</div></fieldset>
    {!journey ? <div className="iw-pending"><MapPin size={28} /><h3>Rota pendente de validação</h3><p>Confirme o endereço completo, a escala e o transporte de retorno com a pessoa. Não há dados suficientes para exibir tempos ou custos confiáveis.</p><p>Origem e destino não foram geocodificados. A confirmação abaixo registra apenas que a pendência foi analisada.</p></div> : <>
      <div className="iw-mobility-inputs"><label>Chegada ao posto<input aria-label="Chegada ao posto" type="time" required value={value.arrival} onChange={(e) => e.target.value && update("arrival", e.target.value)} /></label><label>Saída do posto<input aria-label="Saída do posto" type="time" required value={value.departure} onChange={(e) => e.target.value && update("departure", e.target.value)} /></label><label>Folga na chegada<select aria-label="Folga na chegada" value={value.buffer} onChange={(e) => update("buffer", Number(e.target.value))}>{[0, 5, 10, 15, 20, 30].map((n) => <option key={n} value={n}>{n} min</option>)}</select></label></div>
      <div className="iw-route-heading"><h3>Percurso de {direction === "outbound" ? "ida" : "volta"}</h3><div className="iw-segment" role="group" aria-label="Sentido do percurso"><button type="button" aria-pressed={direction === "outbound"} onClick={() => setDirection("outbound")}>Ida</button><button type="button" aria-pressed={direction === "inbound"} onClick={() => setDirection("inbound")}>Volta</button></div></div>
      <div className="iw-route-metrics"><div><Clock size={18} /><b aria-label="Duração do percurso">{total(legs, "minutes")} min</b><small>por percurso</small></div><div><Bus size={18} /><b>{legs.filter((leg) => leg.kind === "bus").length} condução(ões)</b><small>{money(total(legs, "fare"))} por trecho</small></div><div><PersonSimpleWalk size={18} /><b>{total(legs, "meters")} m</b><small>{total(legs.filter((leg) => leg.kind === "walk"), "minutes")} min a pé</small></div></div>
      <ol className="iw-route-legs">{legs.map((leg, index) => { const Icon = leg.kind === "walk" ? PersonSimpleWalk : Bus; return <li key={index}><span><Icon size={19} /></span><div><b>{leg.label}</b><small>{leg.kind === "walk" ? `${leg.meters} m · sem tarifa` : `${money(leg.fare)} · tarifa de exemplo`}</small></div><b>{leg.minutes} min</b></li>; })}</ol>
      <div className="iw-schedule"><span>{direction === "outbound" ? "Sair de casa às" : "Chegada em casa"}<b>{direction === "outbound" ? clockTime(timeMinutes(value.arrival) - total(legs, "minutes") - value.buffer) : clockTime(timeMinutes(value.departure) + total(legs, "minutes"))}</b></span><p>{direction === "outbound" ? `${total(legs, "minutes")} min de percurso + ${value.buffer} min de folga antes das ${value.arrival}.` : `Saída às ${value.departure} + ${total(legs, "minutes")} min de percurso.`} Horários estimados, sem trânsito ou espera adicional.</p></div>
      <div className="iw-costs"><div><small>Custo diário · ida + volta</small><b>{money(daily)}</b></div><label>Dias presenciais no mês<select aria-label="Dias presenciais no mês" value={value.days} onChange={(e) => update("days", Number(e.target.value))}>{Array.from({ length: 31 }, (_, i) => i + 1).map((n) => <option key={n} value={n}>{n} dias</option>)}</select></label><div><small>Estimativa mensal</small><b aria-label="Custo mensal estimado">{money(daily * value.days)}</b><small>{money(daily)} × {value.days} dias</small></div></div>
      <details className="iw-method"><summary>Como a simulação foi calculada</summary><p>Duração = soma dos trechos a pé e de transporte. Custo diário = tarifas da ida + tarifas da volta. Estimativa mensal = custo diário × dias presenciais. Sem desconto de integração, espera extra, feriados ou alterações de tarifa. Mudar os horários ajusta apenas a aritmética da previsão; não recalcula a rota.</p></details>
    </>}
    <div className="iw-review-checks"><h3>Conferência com o candidato</h3><label><input type="checkbox" checked={value.addressConfirmed} onChange={(e) => update("addressConfirmed", e.target.checked)} /> Origem e destino discutidos na entrevista</label><label><input type="checkbox" checked={value.scheduleConfirmed} onChange={(e) => update("scheduleConfirmed", e.target.checked)} /> Escala e opções de ida e volta discutidas</label><label>Observações de mobilidade<textarea aria-label="Observações de mobilidade" value={value.notes} onChange={(e) => update("notes", e.target.value)} placeholder="Registre dúvidas sobre trajeto, horários ou transporte…" /></label></div>
    <button type="button" className="iw-review-button" aria-pressed={reviewed} onClick={onReview}><CheckCircle size={18} weight={reviewed ? "fill" : "regular"} />{reviewed ? "Mobilidade analisada" : "Marcar mobilidade como analisada"}</button><p className="iw-fine-print">A mobilidade apoia a conversa. Não aprova nem reprova automaticamente uma pessoa.</p>
  </section>;
}
