import { useState } from "react";
import { ArrowRight, CalendarBlank, CheckCircle, Clock, ListBullets, MapPin, TrendUp, UserCircle, UserMinus, UsersThree, WarningCircle, WhatsappLogo, X } from "@phosphor-icons/react";
import { WelcomeIntro } from "./WelcomeIntro.jsx";
import { StatusPill } from "./StatusPill.jsx";
import { getEvidenceLabel } from "./evidenceLabels.js";

const interviewItems = [
  { name: "Rafael Santos", initials: "RS", stage: "Entrevista RH", time: "Hoje, 14:00", owner: "Letícia Silva", tone: "success", status: "Confirmada", color: "plum", role: "Auxiliar de Serviços Gerais", location: "Pavuna · Rio de Janeiro", duration: "45 min previstos", checklist: "Currículo revisado" },
  { name: "Mariana Lima", initials: "ML", stage: "Entrevista Gestor", time: "Amanhã, 10:30", owner: "Carlos Almeida", tone: "info", status: "A confirmar", color: "amber", role: "Auxiliar de Limpeza", location: "Tijuca · Rio de Janeiro", duration: "45 min previstos", checklist: "Mobilidade analisada" },
  { name: "André Cardoso", initials: "AC", stage: "Entrevista RH", time: "25/04, 09:00", owner: "Letícia Silva", tone: "neutral", status: "Agendada", color: "blue", role: "Porteiro", location: "Santa Cruz · Rio de Janeiro", duration: "30 min previstos", checklist: "Confirmação pendente" },
];

const stageLabels = { application: "Candidatura", screening: "Triagem", contact: "Contato", interview_hr: "Entrevista RH", manager_interview: "Entrevista Gestor", survey: "Pesquisa", documents: "Entrega de documentos", training: "Treinamento", hiring: "Contratação" };

const rejectedCandidates = [
  { name: "Camila Souza", initials: "CS", role: "Auxiliar de Serviços Gerais", source: "Site da empresa", reason: "Sem disponibilidade para escala 6×1", date: "Hoje, 08:45", stage: "Triagem", owner: "Ana Marques" },
  { name: "João Martins", initials: "JM", role: "Porteiro", source: "Indeed", reason: "Mobilidade incompatível com o horário", date: "Ontem, 15:20", stage: "Contato", owner: "Lucas" },
  { name: "Lívia Araújo", initials: "LA", role: "Recepcionista", source: "RioVagas", reason: "Experiência obrigatória não comprovada", date: "21/04, 17:05", stage: "Triagem", owner: "Fernanda Silva" },
];

function ChannelMark({ brand }) {
  if (brand === "whatsapp") return <span className="channel-mark is-whatsapp" aria-label="WhatsApp"><WhatsappLogo weight="fill" size={22} /></span>;
  const labels = { rio: "RV", alpha: "AR", indeed: "in", linkedin: "in" };
  return <span className={`channel-mark is-${brand}`} aria-label={brand === "rio" ? "RioVagas" : brand === "alpha" ? "Alpha RH" : brand === "indeed" ? "Indeed" : "LinkedIn"}>{labels[brand]}</span>;
}

export function VacancySummary({ candidates, stages, vacancy }) {
  const activeStages = stages.filter((stage) => candidates.some((candidate) => candidate.stage === stage.id));
  return <section className="vacancy-workspace-view">
    <header className="vacancy-view-heading"><div><h2>Resumo da vaga</h2><p>Visão rápida do processo seletivo, do volume e dos próximos movimentos.</p></div></header>
    <div className="vacancy-summary-metrics"><Metric icon={<UsersThree />} value={candidates.length} label="candidatos no processo" /><Metric icon={<TrendUp />} value={`${activeStages.length}/${stages.length}`} label="etapas com movimento" /><Metric icon={<Clock />} value="2" label="entrevistas hoje" /><Metric icon={<CheckCircle />} value="4" label="vagas em aberto" /></div>
    <div className="vacancy-summary-grid"><section className="vacancy-detail-card"><h3>Andamento do processo</h3><p>Distribuição atual entre as etapas do funil.</p><div className="vacancy-stage-summary">{stages.slice(0, 6).map((stage) => { const total = candidates.filter((candidate) => candidate.stage === stage.id).length; return <div key={stage.id}><span><b>{stage.label}</b><small>{total} candidatos</small></span><i><em style={{ width: `${Math.max(6, total * 18)}%`, background: stage.color }} /></i></div>; })}</div></section><section className="vacancy-detail-card"><h3>Dados da vaga</h3><dl className="vacancy-facts"><div><dt>Função</dt><dd>{vacancy?.role || "Não informada"}</dd></div><div><dt>Posto</dt><dd>{vacancy?.post || "Não informado"}</dd></div><div><dt>Responsável</dt><dd>{vacancy?.owner || "RH"}</dd></div><div><dt>Status</dt><dd>{vacancy?.status || "Ativa"}</dd></div></dl><strong>Próxima ação</strong><small>Confirmar entrevistas da semana e registrar os pareceres.</small></section></div>
  </section>;
}

export function CandidateList({ candidates, onOpen }) {
  return <section className="vacancy-workspace-view candidate-list-view"><header className="vacancy-view-heading"><div className="vacancy-heading-with-icon"><span><ListBullets size={20} /></span><div><h2>Candidatos em lista</h2><p>{candidates.length} pessoas encontradas com os filtros atuais.</p></div></div><span className="workspace-result-count">{candidates.length} resultados</span></header><section className="vacancy-detail-card vacancy-candidate-list"><div className="vacancy-list-head"><span>Candidato</span><span>Etapa atual</span><span>Evidências</span><span>Mobilidade</span><span>Disponibilidade</span><span>Ação</span></div>{candidates.map((candidate) => <article key={`${candidate.id}-${candidate.stage}`}><span className="candidate-list-person">{candidate.photo ? <img src={candidate.photo} alt="" /> : <span className="candidate-list-avatar">{candidate.initials}</span>}<span><b>{candidate.name}</b><small>{candidate.role}</small><small>{candidate.source}</small></span></span><span><span className="candidate-stage-badge">{stageLabels[candidate.stage] ?? candidate.stage}</span></span><span><span className={`evidence-badge ${candidate.evidenceTone}`}>{getEvidenceLabel(candidate.evidence)}</span></span><span className="candidate-list-signal"><MapPin size={16} />{candidate.route}</span><span className="candidate-list-signal"><CalendarBlank size={16} />{candidate.availability}</span><button className="secondary-action candidate-row-action" type="button" aria-label={`Ver perfil de ${candidate.name}`} onClick={() => onOpen(candidate)}><UserCircle size={16} />Ver perfil<ArrowRight size={14} /></button></article>)}</section></section>;
}

export function RejectedCandidates() {
  const [selectedRecord, setSelectedRecord] = useState(null);
  return <section className="vacancy-workspace-view rejected-candidates-view"><header className="vacancy-view-heading"><div className="vacancy-heading-with-icon"><span><UserMinus size={20} /></span><div><h2>Candidatos desclassificados</h2><p>Histórico preservado para rastreabilidade e revisão das decisões.</p></div></div><span className="workspace-result-count">12 registros</span></header><section className="rejected-summary-strip"><span><WarningCircle size={17} />3 registros recentes</span><small>Os demais permanecem disponíveis no histórico demonstrativo.</small></section><section className="vacancy-detail-card vacancy-rejected-list"><div className="rejected-list-head"><span>Candidato</span><span>Motivo</span><span>Etapa de origem</span><span>Registro</span><span>Situação</span><span>Ação</span></div>{rejectedCandidates.map((candidate) => <article key={candidate.name}><span className="candidate-list-person"><span className="candidate-list-avatar is-rejected">{candidate.initials}</span><span><b>{candidate.name}</b><small>{candidate.role}</small><small>{candidate.source}</small></span></span><p className="rejection-reason"><WarningCircle size={16} />{candidate.reason}</p><span className="candidate-stage-badge">{candidate.stage}</span><span className="rejected-record-meta"><b>{candidate.date}</b><small>por {candidate.owner}</small></span><StatusPill tone="neutral">Registrado</StatusPill><button className="secondary-action candidate-row-action" type="button" aria-label={`Ver registro de ${candidate.name}`} onClick={() => setSelectedRecord(candidate)}>Ver registro<ArrowRight size={14} /></button></article>)}</section>{selectedRecord ? <section className="rejected-record-preview" role="region" aria-label={`Registro de ${selectedRecord.name}`}><header><div><span className="candidate-list-avatar is-rejected">{selectedRecord.initials}</span><span><strong>{selectedRecord.name}</strong><small>{selectedRecord.role} · {selectedRecord.source}</small></span></div><button type="button" aria-label="Fechar registro" onClick={() => setSelectedRecord(null)}><X size={17} /></button></header><dl><div><dt>Motivo registrado</dt><dd>{selectedRecord.reason}</dd></div><div><dt>Etapa de origem</dt><dd>{selectedRecord.stage}</dd></div><div><dt>Data e responsável</dt><dd>{selectedRecord.date} · {selectedRecord.owner}</dd></div></dl><p>Registro demonstrativo somente para consulta. Nenhuma ação altera o processo nesta fase do protótipo.</p></section> : null}</section>;
}

export function InterviewsWorkspace({ onStartInterview, onOpenSummary, onRequestReplacement, results }) {
  const groupedInterviews = [["Entrevistas com RH", interviewItems.filter((item) => item.stage === "Entrevista RH")], ["Entrevistas com gestor", interviewItems.filter((item) => item.stage === "Entrevista Gestor")]];
  return <section className="vacancy-workspace-view interview-list-view"><header className="vacancy-view-heading"><div><h2>Entrevistas da vaga</h2><p>Escolha uma pessoa para revisar o contexto e iniciar uma avaliação focada.</p></div><span className="interview-list-count"><CalendarBlank size={17} />3 entrevistas programadas</span></header><div className="interview-list-guide"><span>1. Revise o currículo</span><span>2. Registre a avaliação</span><span>3. Salve o parecer</span></div><div className="vacancy-interview-groups">{groupedInterviews.map(([title, items]) => <section key={title}><h3>{title}</h3><div className="vacancy-interview-list">{items.map((item) => { const completed = results[item.name]; return <article className="vacancy-detail-card vacancy-interview-card" key={item.name + item.time}><span className="interview-candidate"><span className={`candidate-initials candidate-tone-${item.color}`}>{item.initials}</span><span><strong>{item.name}</strong><small>{item.role}</small><small>{item.location}</small></span></span><span className="interview-schedule"><b><CalendarBlank size={16} />{item.time}</b><small><Clock size={15} />{item.duration}</small><small><UserCircle size={15} />{item.owner}</small></span><span className="interview-readiness"><small>{item.checklist}</small><span><i />{completed ? "Avaliação salva" : item.status}</span></span><div>{completed ? <><StatusPill tone="success">Concluída</StatusPill><button className="secondary-action" type="button" aria-label={`Ver resumo de ${item.name}`} onClick={() => onOpenSummary(item)}>Ver resumo</button><button className="text-action compact" type="button" aria-label={`Iniciar nova entrevista de ${item.name}`} onClick={() => onRequestReplacement(item)}>Iniciar nova</button></> : <><StatusPill tone={item.tone}>{item.status}</StatusPill><button className="primary-action" type="button" aria-label={`Iniciar entrevista de ${item.name}`} onClick={() => onStartInterview(item)}>Iniciar entrevista</button></>}</div></article>; })}</div></section>)}</div></section>;
}

export function InterviewLoading({ interview, onComplete }) {
  return <main className="interview-loading" aria-label={`Iniciando entrevista com ${interview.name}`}>
    <WelcomeIntro message="Iniciando a entrevista" subtitle={`${interview.name} · ${interview.stage}`} onComplete={onComplete} />
  </main>;
}

export function ReplacementConfirmation({ interview, onCancel, onConfirm }) { return <div className="interview-confirmation-backdrop"><section role="dialog" aria-modal="true" aria-label="Substituir avaliação anterior" className="interview-confirmation"><h2>Substituir avaliação anterior?</h2><p>Ao concluir e salvar uma nova entrevista de {interview.name}, a avaliação anterior e suas anotações serão substituídas. Se sair sem concluir, a avaliação anterior será preservada.</p><div><button className="secondary-action" type="button" aria-label="Cancelar nova entrevista" onClick={onCancel}>Cancelar</button><button className="primary-action" type="button" onClick={onConfirm}>Iniciar nova entrevista</button></div></section></div>; }

export function PromotionWorkspace({ publishedChannels, onPublish, onUnpublish }) {
  const channels = [["rioVagas", "RioVagas", "Portal de vagas", "Alcance regional para operações."], ["site", "Site da empresa", "Carreiras Alpha RH", "Publique na página institucional."], ["indeed", "Indeed", "Agregador de vagas", "Amplie a busca por candidatos."], ["linkedin", "LinkedIn", "Rede profissional", "Divulgação para perfis profissionais."], ["whatsapp", "WhatsApp", "Comunidades e indicações", "Envio para a rede de contatos autorizada."]];
  return <section className="vacancy-workspace-view"><header className="vacancy-view-heading"><div><h2>Divulgação da vaga</h2><p>Escolha os canais em que esta vaga deve ser publicada.</p></div></header><section className="vacancy-channel-list">{channels.map(([id, channel, category, detail]) => { const published = publishedChannels[id]; const brand = id === "rioVagas" ? "rio" : id === "site" ? "alpha" : id; return <article className="vacancy-detail-card" key={id}><span><ChannelMark brand={brand} /><span><b>{channel}</b><small>{category}</small></span></span><p>{detail}</p><div><StatusPill tone={published ? "success" : "neutral"}>{published ? "Divulgada" : "Pronta para publicar"}</StatusPill><button className={published ? "secondary-action" : "primary-action"} type="button" aria-label={published ? `Despublicar vaga no ${channel}` : `Divulgar vaga no ${channel}`} onClick={() => published ? onUnpublish(id) : onPublish(id)}>{published ? "Despublicar" : "Divulgar vaga"}</button></div></article>; })}</section></section>;
}

function Metric({ icon, value, label }) { return <article><span>{icon}</span><strong>{value}</strong><small>{label}</small></article>; }
