import { useState } from "react";
import "./administration-users.css";
import { Building2, CheckCircle2, ChevronDown, Info, KeyRound, Mail, MoreVertical, Plus, Search, Settings2, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { ScreenHeader } from "../components/ScreenHeader.jsx";
import { StatusPill } from "../components/StatusPill.jsx";
import { WorkspaceTabs } from "../components/WorkspaceTabs.jsx";
import { adminPosts, adminUsers, recruitmentStages } from "../moduleWorkspaceData.js";

const areas = [{ id: "users", label: "Usuários" }, { id: "structure", label: "Estrutura" }, { id: "settings", label: "Configurações" }];

export function AdministrationScreen() {
  const [area, setArea] = useState("users");
  return <main className="screen-workspace miro-screen admin-reference-screen"><WorkspaceTabs items={areas} active={area} onChange={setArea} ariaLabel="Áreas da administração" />{area === "users" && <UsersView />}{area === "structure" && <StructureView />}{area === "settings" && <SettingsView />}</main>;
}

const accessScreens = [
  ["Hoje no RH", "Visão geral e prioridades"], ["Requisições", "Criação e aprovações"], ["Vagas", "Vagas e candidatos"], ["Candidatos", "Banco de talentos e currículos"], ["Agenda", "Entrevistas e compromissos"], ["Relatórios", "Indicadores demonstrativos"], ["Administração", "Usuários, estrutura e configurações"],
];

function UsersView() {
  const [selectedId, setSelectedId] = useState(2);
  const [isInviteOpen, setInviteOpen] = useState(false);
  const [inviteReady, setInviteReady] = useState(false);
  const [isAccessOpen, setAccessOpen] = useState(false);
  const selected = adminUsers.find((user) => user.id === selectedId) ?? adminUsers[0];
  const enabledScreens = selected.area === "Diretoria" ? accessScreens : accessScreens.slice(0, 5);

  return <>
    <ScreenHeader title="Usuários e permissões" description="Organize quem acessa cada tela do Alpha RH e o que pode fazer nela." actions={<button className="primary-action" onClick={() => { setInviteReady(false); setInviteOpen(true); }}><UserPlus size={17} />Novo usuário</button>} />
    <section className="admin-access-summary"><article><UsersRound /><span><strong>4</strong><small>Usuários ativos</small></span></article><article><Mail /><span><strong>2</strong><small>Convites pendentes</small></span></article><article><ShieldCheck /><span><strong>1</strong><small>Acesso suspenso</small></span></article><div><ShieldCheck size={17} /><span><b>Controle por tela</b><small>Defina menus, dados e ações para cada perfil.</small></span></div></section>
    <section className="admin-management-layout">
      <div className="admin-user-main" onClick={() => setAccessOpen(true)}>
        <div className="surface-panel admin-user-directory"><header><div><span className="report-panel-kicker"><UsersRound size={15} />Diretório de usuários</span><h2>Usuários do sistema</h2><p>Selecione uma pessoa para revisar seus acessos.</p></div><span>{adminUsers.length} cadastrados</span></header><div className="admin-directory-head"><span>Usuário</span><span>Perfil</span><span>Telas liberadas</span><span>Último acesso</span><span>Status</span></div>{adminUsers.map((user) => <button className={`admin-directory-row ${user.id === selected.id ? "selected" : ""}`} key={user.id} onClick={() => setSelectedId(user.id)}><span className="person-cell"><i>{user.initials}</i><b>{user.name}<small>{user.email} · {user.area}</small></b></span><span>{user.profile}</span><span>{user.area === "Diretoria" ? "Todas as telas" : "5 telas"}</span><span>{user.lastAccess}</span><span><StatusPill tone={user.tone}>{user.status}</StatusPill></span></button>)}</div>
      </div>
      <aside className="surface-panel admin-access-detail"><header><div className="avatar-token large">{selected.initials}</div><div><span className="report-panel-kicker">Acesso do usuário</span><h2>{selected.name}</h2><p>{selected.email}</p></div><StatusPill tone={selected.tone}>{selected.status}</StatusPill></header><label className="profile-select">Perfil atribuído<select defaultValue={selected.profile}><option>Acesso integral</option><option>Gestora de recrutamento</option><option>Solicitante</option><option>Acesso restrito</option></select><small>O perfil inicia as permissões; você pode ajustar cada tela abaixo.</small></label><div className="access-detail-heading"><div><h3>Telas liberadas</h3><p>Escolha quais módulos aparecem na navegação deste usuário.</p></div><span>{enabledScreens.length}/{accessScreens.length}</span></div><div className="screen-access-list">{accessScreens.map(([label, description], index) => <label key={label}><input type="checkbox" defaultChecked={selected.area === "Diretoria" || index < 5} /><span><b>{label}</b><small>{description}</small></span><select defaultValue={index < 4 ? "Editar" : "Visualizar"}><option>Editar</option><option>Visualizar</option><option>Sem acesso</option></select></label>)}</div><div className="security-note"><ShieldCheck /><span><strong>Acesso protegido</strong><small>Convites usam um link para a pessoa definir a própria senha.</small></span></div><footer><button className="secondary-action">Cancelar</button><button className="primary-action">Salvar acessos</button></footer></aside>
    </section>
    {isAccessOpen ? <UserAccessDialog user={selected} onClose={() => setAccessOpen(false)} /> : null}
    {isInviteOpen ? <UserInviteDialog ready={inviteReady} onClose={() => setInviteOpen(false)} onSend={() => setInviteReady(true)} /> : null}
  </>;
}

function UserInviteDialog({ ready, onClose, onSend }) {
  return <div className="admin-invite-backdrop"><section className="surface-panel admin-invite-dialog" role="dialog" aria-label="Criar novo usuário"><header><div><span className="report-panel-kicker"><UserPlus size={15} />Novo acesso</span><h2>Criar novo usuário</h2><p>Configure o acesso inicial e envie um convite demonstrativo.</p></div><button aria-label="Fechar" onClick={onClose}>×</button></header><div className="invite-fields"><label>Nome completo<input placeholder="Ex.: Marina Costa" /></label><label>E-mail corporativo<input type="email" placeholder="marina@empresa.com.br" /></label><label>Perfil inicial<select><option>Gestora de recrutamento</option><option>Solicitante</option><option>Acesso restrito</option></select></label></div><fieldset><legend>Telas que a pessoa poderá acessar</legend><div>{accessScreens.map(([label]) => <label key={label}><input aria-label={label} type="checkbox" defaultChecked={["Hoje no RH", "Vagas", "Candidatos"].includes(label)} />{label}</label>)}</div></fieldset>{ready ? <div className="invite-success"><CheckCircle2 /><span><strong>Convite demonstrativo preparado</strong><small>Em produção, a pessoa receberá um link para criar sua senha com segurança.</small></span></div> : null}<footer><button className="secondary-action" onClick={onClose}>Cancelar</button><button className="primary-action" onClick={onSend}><Mail size={16} />Enviar convite</button></footer></section></div>;
}

function UserAccessDialog({ user, onClose }) {
  return <div className="admin-invite-backdrop"><section className="surface-panel admin-invite-dialog admin-user-config-dialog" role="dialog" aria-label={`Configurar acessos de ${user.name}`}><header><div className="admin-config-person"><div className="avatar-token large">{user.initials}</div><div><span className="report-panel-kicker"><ShieldCheck size={15} />Acesso do usuário</span><h2>{user.name}</h2><p>{user.email}</p></div></div><button aria-label="Fechar configurações" onClick={onClose}>×</button></header><label className="profile-select">Perfil atribuído<select defaultValue={user.profile}><option>Acesso integral</option><option>Gestora de recrutamento</option><option>Solicitante</option><option>Acesso restrito</option></select><small>O perfil inicia as permissões; ajuste as telas abaixo quando necessário.</small></label><div className="access-detail-heading"><div><h3>Telas liberadas</h3><p>Defina os módulos e o nível de acesso desta pessoa.</p></div><span>{user.area === "Diretoria" ? "7/7" : "5/7"}</span></div><div className="screen-access-list">{accessScreens.map(([label, description], index) => <label key={label}><input type="checkbox" defaultChecked={user.area === "Diretoria" || index < 5} /><span><b>{label}</b><small>{description}</small></span><select defaultValue={index < 4 ? "Editar" : "Visualizar"}><option>Editar</option><option>Visualizar</option><option>Sem acesso</option></select></label>)}</div><footer><button className="secondary-action" onClick={onClose}>Cancelar</button><button className="primary-action" onClick={onClose}>Salvar acessos</button></footer></section></div>;
}

function LegacyUsersView() {
  const [selectedId, setSelectedId] = useState(2);
  const selected = adminUsers.find((user) => user.id === selectedId) ?? adminUsers[0];
  return <>
    <ScreenHeader title="Usuários e permissões" description="Controle quem pode acessar cada área do sistema." actions={<button className="primary-action"><UserPlus size={17} />Convidar usuário</button>} />
    <section className="admin-user-layout">
      <div className="admin-user-main">
        <div className="admin-metric-row"><article><UsersRound /><span><strong>4</strong><small>Ativos</small></span></article><article><Mail /><span><strong>2</strong><small>Convites pendentes</small></span></article><article><ShieldCheck /><span><strong>1</strong><small>Bloqueado</small></span></article></div>
        <div className="admin-filter-row"><label><Search size={16} /><input placeholder="Buscar por nome, e-mail ou área..." /></label>{["Todas as áreas", "Todos os perfis", "Todos os status"].map((value) => <button key={value}>{value}<ChevronDown size={14} /></button>)}</div>
        <div className="surface-panel operational-table admin-users-table"><div className="op-table-head"><span /><span>Usuário</span><span>E-mail</span><span>Área</span><span>Perfil</span><span>Último acesso</span><span>Status</span><span>Ações</span></div>{adminUsers.map((user) => <button className={`op-table-row ${user.id === selected.id ? "selected" : ""}`} key={user.id} onClick={() => setSelectedId(user.id)}><span><input type="checkbox" checked={user.id === selected.id} readOnly /></span><span className="person-cell"><i>{user.initials}</i><b>{user.name}<small>{user.area}</small></b></span><span>{user.email}</span><span>{user.area}</span><span>{user.profile}</span><span>{user.lastAccess}</span><span><StatusPill tone={user.tone}>{user.status}</StatusPill></span><span><MoreVertical size={15} /></span></button>)}</div>
      </div>
      <aside className="surface-panel admin-user-detail"><header><div className="avatar-token large">{selected.initials}</div><div><h2>{selected.name}</h2><p>{selected.email}</p></div><StatusPill tone={selected.tone}>{selected.status}</StatusPill></header><WorkspaceTabs items={[{ id: "permissions", label: "Permissões" }, { id: "data", label: "Dados do usuário" }, { id: "history", label: "Histórico" }]} active="permissions" onChange={() => {}} ariaLabel="Detalhes do usuário" /><label className="profile-select">Perfil atribuído<select value={selected.profile} readOnly><option>{selected.profile}</option></select><small>{selected.area === "Diretoria" ? "Acesso integral a todas as áreas." : "Acesso conforme as responsabilidades do perfil."}</small></label><h3>Permissões por área do sistema</h3><div className="permission-list">{["Requisições", "Vagas", "Candidatos", "Currículos", "Mobilidade", "Admissão", "Relatórios", "Administração"].map((label, index) => <label key={label}><span><KeyRound size={15} />{label}</span><input type="checkbox" defaultChecked={selected.area === "Diretoria" || index < 5} /><select defaultValue={selected.area === "Diretoria" ? "Todos os postos" : "Postos atribuídos"}><option>Todos os postos</option><option>Postos atribuídos</option></select></label>)}</div><div className="security-note"><ShieldCheck /><span><strong>Segurança</strong><small>Autenticação multifator recomendada · 2 sessões ativas</small></span></div><footer><button className="primary-action">Salvar permissões</button><button className="secondary-action">Revogar sessões</button></footer></aside>
    </section>
  </>;
}

const structureWorkspaces = {
  posts: { title: "Postos", singular: "Posto", description: "Unidades e locais utilizados nas vagas.", rows: adminPosts.map((post) => [post.id, post.name, post.legalName, post.owner, post.city]) },
  departments: { title: "Departamentos", singular: "Departamento", description: "Áreas responsáveis pelas solicitações e aprovações.", rows: [["DEP-001", "Operações", "Escalas e postos operacionais", "Carlos Souza", "12 vagas"], ["DEP-002", "Recursos Humanos", "Recrutamento e admissão", "Ana Marques", "8 vagas"], ["DEP-003", "Jurídico", "Documentação e conformidade", "Marina Lopes", "2 vagas"], ["DEP-004", "Diretoria", "Aprovações estratégicas", "Lucas", "3 vagas"]] },
  contracts: { title: "Contratos", singular: "Contrato", description: "Contratos que vinculam postos, operação e prazo.", rows: [["CTR-2025-014", "Leblon Power", "Vigente até 30/09/2025", "Ana Souza", "4 postos"], ["CTR-2025-022", "Centro Empresarial Rio", "Vigente até 31/12/2025", "Bruno Almeida", "3 postos"], ["CTR-2025-031", "Alpha Serviços", "Vigente até 15/08/2025", "Carla Mendes", "2 postos"], ["CTR-2025-038", "Barra Tower", "Vigente até 28/02/2026", "Diego Lima", "5 postos"]] },
  owners: { title: "Responsáveis", singular: "Responsável", description: "Pessoas que acompanham vagas e operações por estrutura.", rows: [["USR-021", "Ana Souza", "Operações · Leblon Power", "Gestora de operação", "4 postos"], ["USR-034", "Bruno Almeida", "Operações · Centro", "Supervisor regional", "3 postos"], ["USR-052", "Carla Mendes", "RH · Matriz", "Analista de RH", "2 postos"], ["USR-067", "Diego Lima", "Operações · Barra", "Coordenador de contrato", "5 postos"]] },
};

function StructureView() {
  const [workspace, setWorkspace] = useState("posts");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const current = structureWorkspaces[workspace];
  const selected = current.rows[selectedIndex] ?? current.rows[0];
  const selectWorkspace = (next) => { setWorkspace(next); setSelectedIndex(0); };
  return <><ScreenHeader title="Postos, departamentos e responsáveis" description="Organize a estrutura utilizada nas requisições e vagas." /><div className="info-strip"><Info /><span>Dados apresentados neste ambiente são <strong>demonstrativos</strong> e servem para configurar a operação.</span></div><WorkspaceTabs items={[{ id: "posts", label: "Postos" }, { id: "departments", label: "Departamentos" }, { id: "contracts", label: "Contratos" }, { id: "owners", label: "Responsáveis" }]} active={workspace} onChange={selectWorkspace} ariaLabel="Estrutura organizacional" /><section className="structure-browser"><div><div className="admin-filter-row"><label><Search size={16} /><input placeholder={`Buscar ${current.title.toLowerCase()}...`} /></label><button>Ativos<ChevronDown size={14} /></button><button>Todos os responsáveis<ChevronDown size={14} /></button></div><div className="surface-panel structure-table"><header><div><span className="report-panel-kicker"><Building2 size={15} />Estrutura organizacional</span><h2>{current.title}</h2><p>{current.description}</p></div><span>{current.rows.length} cadastrados</span></header><div className="structure-table-head"><span>Código</span><span>{current.singular}</span><span>Vínculo</span><span>Responsável</span><span>Escopo</span></div>{current.rows.map((row, index) => <button className={selectedIndex === index ? "selected" : ""} key={row[0]} onClick={() => setSelectedIndex(index)}><span>{row[0]}</span><span><b>{row[1]}</b></span><span>{row[2]}</span><span>{row[3]}</span><span>{row[4]}</span></button>)}</div></div><aside className="surface-panel structure-detail"><header><div className="avatar-token"><Building2 /></div><div><span className="report-panel-kicker">{current.singular} selecionado</span><h2>{selected[1]}</h2><p>{selected[0]}</p></div><StatusPill tone="success">Ativo</StatusPill></header><section><h3>Informações principais</h3><dl><div><dt>Vínculo</dt><dd>{selected[2]}</dd></div><div><dt>Responsável</dt><dd>{selected[3]}</dd></div><div><dt>Escopo</dt><dd>{selected[4]}</dd></div></dl></section><section><h3>Uso no recrutamento</h3><p>Esta estrutura pode ser associada às requisições, vagas e responsáveis do processo.</p></section><footer><button className="secondary-action">Ver histórico</button><button className="primary-action">Editar dados</button></footer></aside></section></>;
}

function LegacyStructureView() {
  const [selectedId, setSelectedId] = useState("CLI-0001");
  const selected = adminPosts.find((post) => post.id === selectedId) ?? adminPosts[0];
  return <>
    <ScreenHeader title="Postos, departamentos e responsáveis" description="Organize a estrutura utilizada nas requisições e vagas." />
    <div className="info-strip"><Info /><span>Dados dos postos são consultados do Weboper em modo <strong>somente leitura</strong>.</span></div>
    <WorkspaceTabs items={[{ id: "posts", label: "Postos" }, { id: "departments", label: "Departamentos" }, { id: "contracts", label: "Contratos" }, { id: "owners", label: "Responsáveis" }]} active="posts" onChange={() => {}} ariaLabel="Estrutura organizacional" />
    <section className="structure-layout"><div><div className="admin-filter-row"><label><Search size={16} /><input placeholder="Buscar por nome, razão social, município ou ID..." /></label>{["Ativo", "Todos os municípios", "Todas as UFs"].map((value) => <button key={value}>{value}<ChevronDown size={14} /></button>)}</div><div className="surface-panel operational-table post-table"><div className="op-table-head"><span>ID Weboper</span><span>Nome fantasia</span><span>Razão social</span><span>Endereço</span><span>Município/UF</span><span>Responsável</span><span>Situação</span><span>Última sincronização</span></div>{adminPosts.map((post) => <button className={`op-table-row ${post.id === selected.id ? "selected" : ""}`} key={post.id} onClick={() => setSelectedId(post.id)}><span>{post.id}</span><span><b>{post.name}</b></span><span>{post.legalName}</span><span>{post.address}</span><span>{post.city}</span><span>{post.owner}</span><span><StatusPill tone="success">Ativo</StatusPill></span><span>{post.lastSync}</span></button>)}</div></div><aside className="surface-panel post-detail"><header><div className="avatar-token"><Building2 /></div><div><h2>{selected.name}</h2><p>Posto (Weboper)</p><small>Dados consultados em modo somente leitura</small></div><StatusPill tone="success">Ativo</StatusPill></header><section><h3>Identificação no Weboper</h3><dl><div><dt>ID original</dt><dd>{selected.id}</dd></div><div><dt>Fonte</dt><dd>CAD_CLIENTE</dd></div></dl></section><section><h3>Informações do posto</h3><dl className="stacked"><div><dt>Nome fantasia</dt><dd>{selected.name}</dd></div><div><dt>Razão social</dt><dd>{selected.legalName}</dd></div><div><dt>Endereço</dt><dd>{selected.address}</dd></div><div><dt>Município / UF</dt><dd>{selected.city}</dd></div></dl></section><section><h3>Sincronização</h3><dl><div><dt>Situação</dt><dd><StatusPill tone="success">Ativo</StatusPill></dd></div><div><dt>Última sincronização</dt><dd>{selected.lastSync}</dd></div></dl><small>Campos previstos: nome, razão social, endereço, município/UF e situação.</small></section><section><h3>Configuração local de recrutamento</h3><dl><div><dt>Responsável pelas operações</dt><dd>{selected.owner}</dd></div><div><dt>Responsável de RH</dt><dd>Ana Marques</dd></div></dl></section><footer><button className="secondary-action">Atualizar dados locais</button><button className="secondary-action">Ver histórico</button></footer></aside></section>
  </>;
}

function SettingsView() {
  const [selectedOrder, setSelectedOrder] = useState(2);
  const selected = recruitmentStages.find((stage) => stage.order === selectedOrder) ?? recruitmentStages[0];
  return <>
    <ScreenHeader title="Configurações do recrutamento" description="Padronize opções utilizadas no processo seletivo." />
    <WorkspaceTabs items={[{ id: "stages", label: "Etapas" }, { id: "sources", label: "Fontes" }, { id: "tags", label: "Tags" }, { id: "rejection", label: "Motivos de desclassificação" }, { id: "closure", label: "Motivos de encerramento" }]} active="stages" onChange={() => {}} ariaLabel="Configurações do recrutamento" />
    <section className="settings-layout"><div><div className="surface-panel stages-panel"><header><div><h2>Etapas do processo seletivo</h2><p>Organize e personalize as etapas do processo.</p></div><button className="primary-action"><Plus size={16} />Adicionar etapa</button></header><div className="op-table-head"><span /><span>Nome</span><span>SLA</span><span>Cor</span><span>Automação vinculada</span><span>Ativa</span><span>Ações</span></div>{recruitmentStages.map((stage) => <button className={`op-table-row ${selected.order === stage.order ? "selected" : ""}`} onClick={() => setSelectedOrder(stage.order)} key={stage.order}><span className="stage-order">{stage.order}</span><span><b>{stage.name}</b></span><span>{stage.sla}</span><span className="stage-color"><i style={{ background: stage.color }} />{stage.color}</span><span>{stage.automation}</span><span><input type="checkbox" defaultChecked /></span><span><MoreVertical size={15} /></span></button>)}</div><div className="surface-panel rejection-reasons"><div><h2>Motivos de desclassificação</h2><p>Somente critérios profissionais relacionados à vaga.</p></div>{["Requisito obrigatório não atendido", "Indisponibilidade de escala", "Experiência incompatível", "Candidato desistiu"].map((reason) => <span key={reason}>{reason}</span>)}<button><Plus size={14} />Adicionar motivo</button></div></div><aside className="surface-panel stage-detail"><header><h2>Configuração da etapa</h2><StatusPill tone="success">Etapa ativa</StatusPill></header><label>Nome da etapa<input value={selected.name} readOnly /></label><div className="split-fields"><label>SLA (prazo)<input value={selected.sla} readOnly /></label><label>Responsável padrão<select><option>Recrutador</option></select></label></div><label>Cor da etapa<span className="color-input"><i style={{ background: selected.color }} />{selected.color}</span></label><h3>Requisitos de entrada</h3><div className="requirement-checks"><label><input type="checkbox" defaultChecked />CV anexado</label><label><input type="checkbox" />Respostas ao questionário</label><label><input type="checkbox" defaultChecked />Dados pessoais completos</label><label><input type="checkbox" />Aprovação da etapa anterior</label></div><h3>Automação vinculada</h3><div className="automation-card"><Mail /><span><strong>{selected.automation}</strong><small>A ação será executada somente após confirmação da movimentação.</small></span></div><div className="detail-notice"><Info /><span><strong>Última alteração</strong><small>Alterado por Lucas em 22/04/2025 09:15.</small></span></div><footer><button className="secondary-action">Cancelar</button><button className="primary-action">Salvar alterações</button></footer></aside></section>
  </>;
}
