export const stages = [
  { id: "application", label: "Candidatura", sla: "2 dias úteis", color: "#1677f2" },
  { id: "screening", label: "Triagem", sla: "2 dias úteis", color: "#7c3aed" },
  { id: "contact", label: "Contato", sla: "1 dia útil", color: "#08a7c4" },
  { id: "interview_hr", label: "Entrevista RH", sla: "3 dias úteis", color: "#f59e0b" },
  { id: "manager_interview", label: "Entrevista Gestor", sla: "3 dias úteis", color: "#e8791a" },
  { id: "research", label: "Pesquisa", sla: "2 dias úteis", color: "#d946ef" },
  { id: "documents", label: "Entrega de documentos", sla: "3 dias úteis", color: "#9333ea" },
  { id: "training", label: "Treinamento", sla: "Conforme programação", color: "#4f46e5" },
  { id: "hiring", label: "Contratação", sla: "2 dias úteis", color: "#16a34a" },
];

const initialCandidatesData = [
  {
    id: 1,
    name: "Rafael Santos",
    initials: "RS",
    photo: "https://i.pravatar.cc/96?img=12",
    source: "RioVagas Gmail",
    stage: "application",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "42 min · 1 condução",
    fare: "R$ 12,40/dia",
    stageTime: "1h30 na etapa",
    owner: "Lucas",
    messages: 2,
    duplicate: "Currículo reenviado · 3 envios",
    role: "Auxiliar de Serviços Gerais",
    location: "Pavuna, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "4 anos em limpeza e conservação",
  },
  {
    id: 2,
    name: "Juliana Alves",
    initials: "JA",
    photo: "https://i.pravatar.cc/96?img=47",
    source: "Site da empresa",
    stage: "application",
    evidence: "Declarado",
    evidenceTone: "info",
    requirements: "2/3 comprovados",
    route: "35 min · 2 conduções",
    fare: "R$ 19,80/dia",
    stageTime: "2h15 na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Auxiliar de Limpeza",
    location: "Botafogo, Rio de Janeiro · RJ",
    availability: "Disponível em 7 dias",
    education: "Ensino médio completo",
    experience: "2 anos em limpeza comercial",
  },
  {
    id: 3,
    name: "Paulo Henrique",
    initials: "PH",
    source: "Indeed",
    stage: "application",
    evidence: "Informação ausente",
    evidenceTone: "warning",
    requirements: "1/3 comprovados",
    route: "Mobilidade pendente",
    fare: "Endereço incompleto",
    stageTime: "3h20 na etapa",
    owner: "Lucas",
    messages: 3,
    role: "Auxiliar Operacional",
    location: "Rio de Janeiro · RJ",
    availability: "A confirmar",
    education: "Não informado",
    experience: "Experiência a confirmar",
  },
  {
    id: 4,
    name: "Mariana Lima",
    initials: "ML",
    photo: "https://i.pravatar.cc/96?img=32",
    source: "Quickin",
    stage: "screening",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "38 min · 2 conduções",
    fare: "R$ 21,40/dia",
    stageTime: "2h50 na etapa",
    owner: "Lucas",
    messages: 2,
    role: "Auxiliar de Limpeza",
    location: "Tijuca, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "3 anos em limpeza hospitalar",
  },
  {
    id: 5,
    name: "André Cardoso",
    initials: "AC",
    photo: "https://i.pravatar.cc/96?img=11",
    source: "LinkedIn",
    stage: "screening",
    evidence: "Declarado",
    evidenceTone: "info",
    requirements: "2/3 comprovados",
    route: "Volta a conferir",
    fare: "Saída após 23h",
    stageTime: "4h10 na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Porteiro",
    location: "Santa Cruz, Rio de Janeiro · RJ",
    availability: "Disponível em 15 dias",
    education: "Ensino médio completo",
    experience: "5 anos como porteiro",
  },
  {
    id: 6,
    name: "Fernanda Rocha",
    initials: "FR",
    photo: "https://i.pravatar.cc/96?img=44",
    source: "WhatsApp",
    stage: "screening",
    evidence: "Informação ausente",
    evidenceTone: "warning",
    requirements: "1/3 comprovados",
    route: "45 min · 1 condução",
    fare: "R$ 12,40/dia",
    stageTime: "5h05 na etapa",
    owner: "Lucas",
    messages: 3,
    role: "Supervisora de Limpeza",
    location: "Centro, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "6 anos em liderança de equipe",
  },
  {
    id: 7,
    name: "Beatriz Nunes",
    initials: "BN",
    photo: "https://i.pravatar.cc/96?img=49",
    source: "Site da empresa",
    stage: "contact",
    evidence: "Declarado",
    evidenceTone: "info",
    requirements: "3/3 comprovados",
    route: "32 min · 1 condução",
    fare: "R$ 16,90/dia",
    stageTime: "1h20 na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Recepcionista",
    location: "Tijuca, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "2 anos em recepção",
  },
  {
    id: 8,
    name: "Rafael Costa",
    initials: "RC",
    source: "RioVagas Gmail",
    stage: "contact",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "40 min · 2 conduções",
    fare: "R$ 22,15/dia",
    stageTime: "1h05 na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Auxiliar de Serviços Gerais",
    location: "Méier, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "4 anos em serviços gerais",
  },
  {
    id: 9,
    name: "Eduardo Silva",
    initials: "ES",
    source: "LinkedIn",
    stage: "contact",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "45 min · 2 conduções",
    fare: "R$ 24,60/dia",
    stageTime: "50 min na etapa",
    owner: "Lucas",
    messages: 2,
    role: "Auxiliar Operacional",
    location: "Duque de Caxias · RJ",
    availability: "A confirmar",
    education: "Ensino médio completo",
    experience: "1 ano como auxiliar operacional",
  },
  {
    id: 10,
    name: "Mariana Lima",
    initials: "ML",
    photo: "https://i.pravatar.cc/96?img=32",
    source: "Quickin",
    stage: "interview_hr",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "38 min · 2 conduções",
    fare: "R$ 16,90/dia",
    stageTime: "30 min na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Auxiliar de Limpeza",
    location: "Tijuca, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "3 anos em limpeza hospitalar",
  },
  {
    id: 11,
    name: "André Cardoso",
    initials: "AC",
    photo: "https://i.pravatar.cc/96?img=11",
    source: "LinkedIn",
    stage: "interview_hr",
    evidence: "Declarado",
    evidenceTone: "info",
    requirements: "2/3 comprovados",
    route: "Volta a conferir",
    fare: "Saída após 23h",
    stageTime: "1d 04h na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Porteiro",
    location: "Santa Cruz, Rio de Janeiro · RJ",
    availability: "Disponível em 15 dias",
    education: "Ensino médio completo",
    experience: "5 anos como porteiro",
  },
  {
    id: 12,
    name: "Rafael Santos",
    initials: "RS",
    photo: "https://i.pravatar.cc/96?img=12",
    source: "RioVagas Gmail",
    stage: "manager_interview",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "42 min · 1 condução",
    fare: "R$ 24,10/dia",
    stageTime: "1d 03h na etapa",
    owner: "Lucas",
    messages: 2,
    role: "Auxiliar de Serviços Gerais",
    location: "Pavuna, Rio de Janeiro · RJ",
    availability: "Disponível agora",
    education: "Ensino médio completo",
    experience: "4 anos em limpeza e conservação",
  },
  {
    id: 13,
    name: "Fernanda Rocha",
    initials: "FR",
    photo: "https://i.pravatar.cc/96?img=44",
    source: "Indeed",
    stage: "hiring",
    evidence: "Comprovado",
    evidenceTone: "success",
    requirements: "3/3 comprovados",
    route: "32 min · 1 condução",
    fare: "R$ 18,50/dia",
    stageTime: "2d 03h na etapa",
    owner: "Lucas",
    messages: 1,
    role: "Supervisora de Limpeza",
    location: "Centro, Rio de Janeiro · RJ",
    availability: "Contratação em andamento",
    education: "Ensino médio completo",
    experience: "6 anos em liderança de equipe",
  },
];

export const initialCandidates = initialCandidatesData.map((candidate) => ({ ...candidate, isDemo: true }));
