import { useState } from "react";
import { Building2, CheckCircle2, ChevronDown, Info, KeyRound, Mail, MoreVertical, Plus, Search, Settings2, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { ScreenHeader } from "../components/ScreenHeader.jsx";
import { StatusPill } from "../components/StatusPill.jsx";
import { WorkspaceTabs } from "../components/WorkspaceTabs.jsx";
import { adminPosts, adminUsers, recruitmentStages } from "../moduleWorkspaceData.js";

const areas = [{ id: "users", label: "Usuários" }, { id: "structure", label: "Estrutura" }, { id: "settings", label: "Configurações" }];

export function AdministrationScreen() {
  const [area, setArea] = useState("users");
  return <main className="screen-workspace miro-screen admin-reference-screen"><WorkspaceTabs items={areas} active={area} onChange={setArea} ariaLabel="Áreas da administração" />{area === "users" && <UsersView />}{area === "structure" && <StructureView />}{area === "settings" && <SettingsView />}</main>;
}

function UsersView() {
  const [selectedId, setSelectedId] = useState(2);
  const selected = adminUsers.find((user) => user.id === selectedId) ?? adminUsers[0];
  return <>
    <ScreenHeader title="Usuários e permissões" description="Controle quem pode acessar cada área do sistema." actions={<button className="primary-action"><UserPlus size={17} />Convidar usuário</button>} />
    <section className="admin-user-layout">
      <div className="admin-user-main">
        <div className="admin-metric-row"><article><UsersRound /><span><strong>4</strong><small>Ativos</small></span></article><article><Mail /><span><strong>2</strong><small>Convites pendentes</small></span></article><article><ShieldCheck /><span><strong>1</strong><small>Bloqueado</small></span></article></div>
        <div className="admin-filter-row"><label><Search size={16} /><input placeholder="Buscar por nome, e-mail ou área..." /></label>{["Todas as áreas", "Todos os perfis", "Todos os status"].map((value) => <button key={value}>{value}<ChevronDown size={14} /></button>)}</div>
        <div className="surface-panel operational-table admin-users-table"><div className="op-table-head"><span /><span>Usuário</span><span>E-mail</span><span>Área</span><span>Perfil</span><span>Último acesso</span><span>Status</span><span>Ações</span></div>{adminUsers.map((user) => <button className={`op-table-row ${user.id === selected.id ? "selected" : ""}`} key={user.id} onClick={() => setSelectedId(user.id)}><span><input type="checkbox" checked={user.id === selected.id} readOnly /></span><span className="person-cell"><i>{user.initials}</i><b>{user.name}<small>{user.area}</small></b></span><span>{user.email}</span><span>{user.area}</span><span>{user.profile}</span><span>{user.lastAccess}</span><span><StatusPill tone={user.tone}>{user.status}</StatusPill></span><span><MoreVertical size={15} /></span></button>)}</div>
      </div>
      <aside className="surface-panel admin-user-detail"><header><div className="avatar-token large">{selected.initials}</div><div><h2>{selected.name}</h2><p>{selected.email}</p></div><StatusPill tone={selected.tone}>{selected.status}</StatusPill></header><WorkspaceTabs items={[{ id: "permissions", label: "Permissões" }, { id: "data", label: "Dados do usuário" }, { id: "history", label: "Histórico" }]} active="permissions" onChange={() => {}} ariaLabel="Detalhes do usuário" /><label className="profile-select">Perfil atribuído<select value={selected.profile} readOnly><option>{selected.profile}</option></select><small>{selected.area === "Diretoria" ? "Acesso integral a todas as áreas." : "Acesso conforme as responsabilidades do perfil."}</small></label><h3>Permissões por área do sistema</h3><div className="permission-list">{["Requisições", "Vagas", "Candidatos", "Currículos", "Mobilidade", "Admissão", "Relatórios", "Administração"].map((label, index) => <label key={label}><span><KeyRound size={15} />{label}</span><input type="checkbox" defaultChecked={selected.area === "Diretoria" || index < 5} /><select defaultValue={selected.area === "Diretoria" ? "Todos os postos" : "Postos atribuídos"}><option>Todos os postos</option><option>Postos atribuídos</option></select></label>)}</div><div className="security-note"><ShieldCheck /><span><strong>Segurança</strong><small>Autenticação multifator recomendada · 2 sessões ativas</small></span></div><footer><button className="primary-action">Salvar permissões</button><button className="secondary-action">Revogar sessões</button></footer></aside>
    </section>
  </>;
}

function StructureView() {
  const [selectedId, setSelectedId] = useState("CLI-0001");
  const selected = adminPosts.find((post) => post.id === selectedId) ?? adminPosts[0];
  return <>
    <ScreenHeader title="Postos, departamentos e responsáveis" description="Organize a estrutura utilizada nas requisições e vagas." />
    <div className="info-strip"><Info /><span>Dados dos postos são consultados do Weboper em modo <strong>somente leitura</strong>.</span></div>
    <WorkspaceTabs items={[{ id: "posts", label: "Postos" }, { id: "departments", label: "Departamentos" }, { id: "contracts", label: "Contratos" }, { id: "owners", label: "Responsáveis" }]} active="posts" onChange={() => {}} ariaLabel="Estrutura organizacional" />
    <section className="structure-layout"><div><div className="admin-filter-row"><label><Search size={16} /><input placeholder="Buscar por nome, razão social, município ou ID..." /></label>{["Ativo", "Todos os municípios", "Todas as UFs"].map((value) => <button key={value}>{value}<ChevronDown size={14} /></button>)}</div><div className="surface-panel operational-table post-table"><div className="op-table-head"><span>ID Weboper</span><span>Nome fantasia</span><span>Razão social</span><span>Endereço</span><span>Município/UF</span><span>Responsável</span><span>Situação</span><span>Última sincronização</span></div>{adminPosts.map((post) => <button className={`op-table-row ${post.id === selected.id ? "selected" : ""}`} key={post.id} onClick={() => setSelectedId(post.id)}><span>{post.id}</span><span><b>{post.name}</b></span><span>{post.legalName}</span><span>{post.address}</span><span>{post.city}</span><span>{post.owner}</span><span><StatusPill tone="success">Ativo</StatusPill></span><span>{post.lastSync}</span></button>)}</div></div><aside className="surface-panel post-detail"><header><div className="avatar-token"><Building2 /></div><div><h2>{selected.name}</h2><p>Posto (Weboper)</p><small>Dados consultados em modo somente leitura</small></div><StatusPill tone="success">Ativo</StatusPill></header><section><h3>Identificação no Weboper</h3><dl><div><dt>ID original</dt><dd>{selected.id}</dd></div><div><dt>Fonte</dt><dd>CAD_CLIENTE</dd></div></dl></section><section><h3>Informações do posto</h3><dl className="stacked"><div><dt>Nome fantasia</dt><dd>{selected.name}</dd></div><div><dt>Razão social</dt><dd>{selected.legalName}</dd></div><div><dt>Endereço</dt><dd>{selected.address}</dd></div><div><dt>Município / UF</dt><dd>{selected.city}</dd></div></dl></section><section><h3>Sincronização</h3><dl><div><dt>Situação</dt><dd><StatusPill tone="success">Ativo</StatusPill></dd></div><div><dt>Última sincronização</dt><dd>{selected.lastSync}</dd></div></dl><small>Campos previstos: nome, razão social, endereço, município/UF e situação.</small></section><section><h3>Configuração local de recrutamento</h3><dl><div><dt>Responsável pelas operações</dt><dd>{selected.owner}</dd></div><div><dt>Responsável de RH</dt><dd>Ana Marques</dd></div></dl></section><footer><button className="secondary-action">Atualizar dados locais</button><button className="secondary-action">Ver histórico</button></footer></aside></section>
  </>;
}

function SettingsView() {
  const [selectedOrder, setSelectedOrder] = useState(2);
  const selected = recruitmentStages.find((stage) => stage.order === selectedOrder) ?? recruitmentStages[0];
  return <>
    <ScreenHeader title="Configurações do recrutamento" description="Padronize opções utilizadas no processo seletivo." />
    <WorkspaceTabs items={[{ id: "stages", label: "Etapas" }, { id: "sources", label: "Fontes" }, { id: "tags", label: "Tags" }, { id: "rejection", label: "Motivos de desclassificação" }, { id: "closure", label: "Motivos de encerramento" }]} active="stages" onChange={() => {}} ariaLabel="Configurações do recrutamento" />
    <section className="settings-layout"><div><div className="surface-panel stages-panel"><header><div><h2>Etapas do processo seletivo</h2><p>Organize e personalize as etapas do processo.</p></div><button className="primary-action"><Plus size={16} />Adicionar etapa</button></header><div className="op-table-head"><span /><span>Nome</span><span>SLA</span><span>Cor</span><span>Automação vinculada</span><span>Ativa</span><span>Ações</span></div>{recruitmentStages.map((stage) => <button className={`op-table-row ${selected.order === stage.order ? "selected" : ""}`} onClick={() => setSelectedOrder(stage.order)} key={stage.order}><span className="stage-order">{stage.order}</span><span><b>{stage.name}</b></span><span>{stage.sla}</span><span className="stage-color"><i style={{ background: stage.color }} />{stage.color}</span><span>{stage.automation}</span><span><input type="checkbox" defaultChecked /></span><span><MoreVertical size={15} /></span></button>)}</div><div className="surface-panel rejection-reasons"><div><h2>Motivos de desclassificação</h2><p>Somente critérios profissionais relacionados à vaga.</p></div>{["Requisito obrigatório não atendido", "Indisponibilidade de escala", "Experiência incompatível", "Candidato desistiu"].map((reason) => <span key={reason}>{reason}</span>)}<button><Plus size={14} />Adicionar motivo</button></div></div><aside className="surface-panel stage-detail"><header><h2>Configuração da etapa</h2><StatusPill tone="success">Etapa ativa</StatusPill></header><label>Nome da etapa<input value={selected.name} readOnly /></label><div className="split-fields"><label>SLA (prazo)<input value={selected.sla} readOnly /></label><label>Responsável padrão<select><option>Recrutador</option></select></label></div><label>Cor da etapa<span className="color-input"><i style={{ background: selected.color }} />{selected.color}</span></label><h3>Requisitos de entrada</h3><div className="requirement-checks"><label><input type="checkbox" defaultChecked />CV anexado</label><label><input type="checkbox" />Respostas ao questionário</label><label><input type="checkbox" defaultChecked />Dados pessoais completos</label><label><input type="checkbox" />Aprovação da etapa anterior</label></div><h3>Automação vinculada</h3><div className="automation-card"><Mail /><span><strong>{selected.automation}</strong><small>A ação será executada somente após confirmação da movimentação.</small></span></div><div className="detail-notice"><Info /><span><strong>Última alteração</strong><small>Alterado por Lucas em 22/04/2025 09:15.</small></span></div><footer><button className="secondary-action">Cancelar</button><button className="primary-action">Salvar alterações</button></footer></aside></section>
  </>;
}
